CREATE TABLE Ingredient (
    ingredient_id INT PRIMARY KEY AUTO_INCREMENT,
    item_name VARCHAR(60) NOT NULL
);

CREATE TABLE Inventory (
    inventory_id INT PRIMARY KEY AUTO_INCREMENT,
    ingredient_id INT,
    quantity INT NOT NULL,
    restock_date DATE,
    FOREIGN KEY (ingredient_id) REFERENCES Ingredient(ingredient_id)
);

INSERT INTO Ingredient (item_name)
VALUES 
('Tomato'), ('Onion'), ('Garlic'), ('Carrot'), ('Bell Pepper'),
('Potato'), ('Cucumber'), ('Spinach'), ('Broccoli'), ('Lettuce'),
('Chicken'), ('Beef'), ('Pork'), ('Fish'), ('Shrimp'),
('Salt'), ('Pepper'), ('Olive Oil'), ('Butter'), ('Milk'),
('Eggs'), ('Cheese'), ('Yogurt'), ('Flour'), ('Sugar'),
('Rice'), ('Pasta'), ('Beans'), ('Lentils'), ('Chickpeas'),
('Basil'), ('Thyme'), ('Parsley'), ('Cinnamon'), ('Vanilla'),
('Oats'), ('Bread'), ('Tofu'), ('Soy Sauce'), ('Tomato Sauce'),
('Honey'), ('Almonds'), ('Walnuts'), ('Peanut Butter'), ('Chocolate'),
('Orange'), ('Apple'), ('Banana'), ('Strawberry'), ('Blueberry');

INSERT INTO Inventory (ingredient_id, quantity, restock_date)
VALUES 
(1, FLOOR(RAND() * 100 + 1), DATE_ADD(CURDATE(), INTERVAL FLOOR(RAND() * 30) DAY)),
(2, FLOOR(RAND() * 100 + 1), DATE_ADD(CURDATE(), INTERVAL FLOOR(RAND() * 30) DAY)),
(3, FLOOR(RAND() * 100 + 1), DATE_ADD(CURDATE(), INTERVAL FLOOR(RAND() * 30) DAY)),
(4, FLOOR(RAND() * 100 + 1), DATE_ADD(CURDATE(), INTERVAL FLOOR(RAND() * 30) DAY)),
(5, FLOOR(RAND() * 100 + 1), DATE_ADD(CURDATE(), INTERVAL FLOOR(RAND() * 30) DAY)),
(6, FLOOR(RAND() * 100 + 1), DATE_ADD(CURDATE(), INTERVAL FLOOR(RAND() * 30) DAY)),
(7, FLOOR(RAND() * 100 + 1), DATE_ADD(CURDATE(), INTERVAL FLOOR(RAND() * 30) DAY)),
(8, FLOOR(RAND() * 100 + 1), DATE_ADD(CURDATE(), INTERVAL FLOOR(RAND() * 30) DAY)),
(9, FLOOR(RAND() * 100 + 1), DATE_ADD(CURDATE(), INTERVAL FLOOR(RAND() * 30) DAY)),
(10, FLOOR(RAND() * 100 + 1), DATE_ADD(CURDATE(), INTERVAL FLOOR(RAND() * 30) DAY)),
(11, FLOOR(RAND() * 100 + 1), DATE_ADD(CURDATE(), INTERVAL FLOOR(RAND() * 30) DAY)),
(12, FLOOR(RAND() * 100 + 1), DATE_ADD(CURDATE(), INTERVAL FLOOR(RAND() * 30) DAY)),
(13, FLOOR(RAND() * 100 + 1), DATE_ADD(CURDATE(), INTERVAL FLOOR(RAND() * 30) DAY)),
(14, FLOOR(RAND() * 100 + 1), DATE_ADD(CURDATE(), INTERVAL FLOOR(RAND() * 30) DAY)),
(15, FLOOR(RAND() * 100 + 1), DATE_ADD(CURDATE(), INTERVAL FLOOR(RAND() * 30) DAY)),
(16, FLOOR(RAND() * 100 + 1), DATE_ADD(CURDATE(), INTERVAL FLOOR(RAND() * 30) DAY)),
(17, FLOOR(RAND() * 100 + 1), DATE_ADD(CURDATE(), INTERVAL FLOOR(RAND() * 30) DAY)),
(18, FLOOR(RAND() * 100 + 1), DATE_ADD(CURDATE(), INTERVAL FLOOR(RAND() * 30) DAY)),
(19, FLOOR(RAND() * 100 + 1), DATE_ADD(CURDATE(), INTERVAL FLOOR(RAND() * 30) DAY)),
(20, FLOOR(RAND() * 100 + 1), DATE_ADD(CURDATE(), INTERVAL FLOOR(RAND() * 30) DAY)),
(21, FLOOR(RAND() * 100 + 1), DATE_ADD(CURDATE(), INTERVAL FLOOR(RAND() * 30) DAY)),
(22, FLOOR(RAND() * 100 + 1), DATE_ADD(CURDATE(), INTERVAL FLOOR(RAND() * 30) DAY)),
(23, FLOOR(RAND() * 100 + 1), DATE_ADD(CURDATE(), INTERVAL FLOOR(RAND() * 30) DAY)),
(24, FLOOR(RAND() * 100 + 1), DATE_ADD(CURDATE(), INTERVAL FLOOR(RAND() * 30) DAY)),
(25, FLOOR(RAND() * 100 + 1), DATE_ADD(CURDATE(), INTERVAL FLOOR(RAND() * 30) DAY)),
(26, FLOOR(RAND() * 100 + 1), DATE_ADD(CURDATE(), INTERVAL FLOOR(RAND() * 30) DAY)),
(27, FLOOR(RAND() * 100 + 1), DATE_ADD(CURDATE(), INTERVAL FLOOR(RAND() * 30) DAY)),
(28, FLOOR(RAND() * 100 + 1), DATE_ADD(CURDATE(), INTERVAL FLOOR(RAND() * 30) DAY)),
(29, FLOOR(RAND() * 100 + 1), DATE_ADD(CURDATE(), INTERVAL FLOOR(RAND() * 30) DAY)),
(30, FLOOR(RAND() * 100 + 1), DATE_ADD(CURDATE(), INTERVAL FLOOR(RAND() * 30) DAY)),
(31, FLOOR(RAND() * 100 + 1), DATE_ADD(CURDATE(), INTERVAL FLOOR(RAND() * 30) DAY)),
(32, FLOOR(RAND() * 100 + 1), DATE_ADD(CURDATE(), INTERVAL FLOOR(RAND() * 30) DAY)),
(33, FLOOR(RAND() * 100 + 1), DATE_ADD(CURDATE(), INTERVAL FLOOR(RAND() * 30) DAY)),
(34, FLOOR(RAND() * 100 + 1), DATE_ADD(CURDATE(), INTERVAL FLOOR(RAND() * 30) DAY)),
(35, FLOOR(RAND() * 100 + 1), DATE_ADD(CURDATE(), INTERVAL FLOOR(RAND() * 30) DAY)),
(36, FLOOR(RAND() * 100 + 1), DATE_ADD(CURDATE(), INTERVAL FLOOR(RAND() * 30) DAY)),
(37, FLOOR(RAND() * 100 + 1), DATE_ADD(CURDATE(), INTERVAL FLOOR(RAND() * 30) DAY)),
(38, FLOOR(RAND() * 100 + 1), DATE_ADD(CURDATE(), INTERVAL FLOOR(RAND() * 30) DAY)),
(39, FLOOR(RAND() * 100 + 1), DATE_ADD(CURDATE(), INTERVAL FLOOR(RAND() * 30) DAY)),
(40, FLOOR(RAND() * 100 + 1), DATE_ADD(CURDATE(), INTERVAL FLOOR(RAND() * 30) DAY)),
(41, FLOOR(RAND() * 100 + 1), DATE_ADD(CURDATE(), INTERVAL FLOOR(RAND() * 30) DAY)),
(42, FLOOR(RAND() * 100 + 1), DATE_ADD(CURDATE(), INTERVAL FLOOR(RAND() * 30) DAY)),
(43, FLOOR(RAND() * 100 + 1), DATE_ADD(CURDATE(), INTERVAL FLOOR(RAND() * 30) DAY)),
(44, FLOOR(RAND() * 100 + 1), DATE_ADD(CURDATE(), INTERVAL FLOOR(RAND() * 30) DAY)),
(45, FLOOR(RAND() * 100 + 1), DATE_ADD(CURDATE(), INTERVAL FLOOR(RAND() * 30) DAY)),
(46, FLOOR(RAND() * 100 + 1), DATE_ADD(CURDATE(), INTERVAL FLOOR(RAND() * 30) DAY)),
(47, FLOOR(RAND() * 100 + 1), DATE_ADD(CURDATE(), INTERVAL FLOOR(RAND() * 30) DAY)),
(48, FLOOR(RAND() * 100 + 1), DATE_ADD(CURDATE(), INTERVAL FLOOR(RAND() * 30) DAY)),
(49, FLOOR(RAND() * 100 + 1), DATE_ADD(CURDATE(), INTERVAL FLOOR(RAND() * 30) DAY)),
(50, FLOOR(RAND() * 100 + 1), DATE_ADD(CURDATE(), INTERVAL FLOOR(RAND() * 30) DAY));